dist: xenial

language: python

fast_finish: true

python:
  - 3.6

cache:
  pip: true

branches:
  only:
    - master

before_install:
  - NUMPY_VERSION=1.14.1 PANDAS_VERSION=0.22.0 SCIPY_VERSION=1.0.0 STATSMODELS_VERSION=0.9.0 PANDAS_DATAREADER_VERSION=0.4.0 DASK_VERSION=0.17.1
  - python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
  - etc/dev-install


install:
  - |
    wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
    tar -xvzf ta-lib-0.4.0-src.tar.gz
    cd ta-lib/
    ./configure --prefix=/usr
    make
    sudo make install
    pip install -r ./etc/requirements_talib.in -c ./etc/requirements_locked.txt


before_script:
  - pip freeze | sort

script:
  - flake8 zipline tests
  - nosetests --with-coverage

after_success:
  - coveralls
