dist: xenial

addons:
  apt:
    packages: 
      - libatlas-base-dev
      - liblapack-dev
      - gfortran
      - libgmp-dev
      - libmpfr-dev
      - libsuitesparse-dev
      - swig
      - libmpc-dev

language: python

fast_finish: true

python:
  - 3.7
  - 3.6

cache:
  pip: true
  ccache: true

branches:
  only:
    - master

jobs:
  allow_failures:
    - python: 3.7

before_install:
  - |
    wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
    tar -xvzf ta-lib-0.4.0-src.tar.gz
    cd ta-lib/
    ./configure --prefix=/usr
    make
    sudo make install
    cd ..

install:
  - python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
  - python -m pip install --no-deps -U pip wheel
  - python -m pip install -r requirements-dev.txt
  - python setup.py build_ext --inplace -q -j2

before_script:
  - pip freeze | sort

script:
  - nosetests --with-coverage

# after_success:
#   - coveralls

