name: zipline-dev
channels:
  - conda-forge
dependencies:
  - python=3.6
  - cython
  - setuptools
  - numpy
  - scipy
  - statsmodels
  - numexpr
  - networkx
  - pandas=0.22
  - pandas-datareader
  - lru-dict

  - empyrical

  - pytz
  - python-dateutil
  - trading-calendars

  - requests

  - sqlalchemy
  - alembic

  - bcolz
  - h5py
  - pytables

  - intervaltree
  - bottleneck

  - iso3166
  - iso4217

  - six
  - python-interface
  - multipledispatch
  - toolz

  - click
  - Logbook

  - coverage
  - nose
  - parameterized
  - nose-timer

  - mock
  - testfixtures
  - responses

  - flake8
  - matplotlib
  - pyyaml

  - pip
  - pip:
    - patsy
    - nose-ignore-docstring
    - TA-Lib