from typing import Any

from numpy import ndarray

class _NoneFirstSortKey:
    def __eq__(self, value, /) -> Any: ...
    def __ge__(self, value, /) -> Any: ...
    def __gt__(self, value, /) -> Any: ...
    __hash__: Any
    def __le__(self, value, /) -> Any: ...
    def __lt__(self, value, /) -> Any: ...
    def __ne__(self, value, /) -> Any: ...

def factorize_strings(values: ndarray, missing_value, sort: int) -> Any: ...
def factorize_strings_known_categories(
    values: ndarray, categories: list, missing_value, sort: bool
) -> Any: ...
def smallest_uint_that_can_hold(maxval: int) -> Any: ...
