from typing import Any

class BarData:
    def __contains__(self, key, /) -> Any: ...
    def __getitem__(self, key, /) -> Any: ...
    def __init__(
        self,
        data_portal,
        simulation_dt_func,
        data_frequency,
        trading_calendar,
        restrictions,
        universe_func=None,
    ) -> None: ...
    def __iter__(self, /) -> Any: ...
    def __len__(self, /) -> Any: ...
    _handle_non_market_minutes: Any
    def can_trade(self, assets) -> Any: ...
    def current(self, assets, fields) -> Any: ...
    def current_chain(self, continuous_future) -> Any: ...
    current_dt: Any
    current_session: Any
    current_session_minutes: Any
    fetcher_assets: Any
    def history(self, assets, fields, bar_count, frequency) -> Any: ...
    def is_stale(self, assets) -> Any: ...
    def items(self) -> Any: ...
    def iterkeys(self) -> Any: ...
    def keys(self) -> Any: ...

class InnerPosition:
    def __init__(
        self, asset, amount=0, cost_basis=0.0, last_sale_price=0.0, last_sale_date=None
    ) -> None: ...
    amount: int
    asset: Any
    cost_basis: float
    last_sale_date: Any
    last_sale_price: float

class SidView:
    def __contains__(self, key, /) -> Any: ...
    def __getitem__(self, key, /) -> Any: ...
    def __init__(
        self, asset, data_portal, simulation_dt_func, data_frequency
    ) -> None: ...
    current_dt: Any
    datetime: Any
    dt: Any
    def mavg(self, num_minutes) -> Any: ...
    def returns(self) -> Any: ...
    sid: Any
    def stddev(self, num_minutes) -> Any: ...
    def vwap(self, num_minutes) -> Any: ...

class check_parameters:
    def __call__(self, /, *args, **kwargs) -> Any: ...
    def __init__(self, keyword_names, types) -> None: ...

def handle_non_market_minutes(bar_data) -> Any: ...
