from collections.abc import Mapping
from typing import ClassVar, Self, SupportsIndex

import numpy as np
import pandas as pd

from zipline.assets.exchange_info import ExchangeInfo

class Asset:
    """Base class for entities that can be owned by a trading algorithm."""

    _kwargnames: ClassVar[frozenset[str]]

    def __init__(
        self,
        sid: int,
        exchange_info: ExchangeInfo,
        symbol: str = "",
        asset_name: str = "",
        start_date: pd.Timestamp | None = None,
        end_date: pd.Timestamp | None = None,
        first_traded: pd.Timestamp | None = None,
        auto_close_date: pd.Timestamp | None = None,
        tick_size: float = 0.01,
        multiplier: float = 1.0,
    ) -> None: ...
    @property
    def sid(self) -> int: ...
    @property
    def exchange_info(self) -> ExchangeInfo: ...
    @property
    def symbol(self) -> str: ...
    @property
    def asset_name(self) -> str: ...
    @property
    def start_date(self) -> pd.Timestamp | None: ...
    @property
    def end_date(self) -> pd.Timestamp | None: ...
    first_traded: pd.Timestamp | None
    @property
    def auto_close_date(self) -> pd.Timestamp | None: ...
    @property
    def tick_size(self) -> float: ...
    @property
    def price_multiplier(self) -> float: ...
    @property
    def exchange(self) -> str: ...
    @property
    def exchange_full(self) -> str: ...
    @property
    def country_code(self) -> str: ...

    # Assets compare and hash as their sids, so they compare with ints too.
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __ne__(self, value: object, /) -> bool: ...
    def __lt__(self, value: SupportsIndex, /) -> bool: ...
    def __le__(self, value: SupportsIndex, /) -> bool: ...
    def __gt__(self, value: SupportsIndex, /) -> bool: ...
    def __ge__(self, value: SupportsIndex, /) -> bool: ...
    def to_dict(self) -> dict[str, object]: ...
    @classmethod
    def from_dict(cls, dict_: Mapping[str, object]) -> Self: ...
    def is_alive_for_session(self, session_label: pd.Timestamp) -> bool: ...
    def is_exchange_open(self, dt_minute: pd.Timestamp) -> bool: ...

class Equity(Asset):
    """Asset subclass representing partial ownership of a company, trust, or
    partnership."""

    @property
    def security_start_date(self) -> pd.Timestamp | None: ...
    @property
    def security_end_date(self) -> pd.Timestamp | None: ...
    @property
    def security_name(self) -> str: ...

class Future(Asset):
    """Asset subclass representing ownership of a futures contract."""

    def __init__(
        self,
        sid: int,
        exchange_info: ExchangeInfo,
        symbol: str = "",
        root_symbol: str = "",
        asset_name: str = "",
        start_date: pd.Timestamp | None = None,
        end_date: pd.Timestamp | None = None,
        notice_date: pd.Timestamp | None = None,
        expiration_date: pd.Timestamp | None = None,
        auto_close_date: pd.Timestamp | None = None,
        first_traded: pd.Timestamp | None = None,
        tick_size: float = 0.001,
        multiplier: float = 1.0,
    ) -> None: ...
    @property
    def root_symbol(self) -> str: ...
    @property
    def notice_date(self) -> pd.Timestamp | None: ...
    @property
    def expiration_date(self) -> pd.Timestamp | None: ...
    @property
    def multiplier(self) -> float:
        """Deprecated: use ``price_multiplier``."""

def make_asset_array(size: int, asset: Asset) -> np.ndarray: ...
