from collections.abc import Callable, Iterable, Mapping, Set
from typing import ClassVar, Literal, Self, SupportsIndex

import numpy as np
import pandas as pd

from zipline.assets._assets import Future
from zipline.assets.exchange_info import ExchangeInfo

#: How a continuous future's prices are adjusted across rolls: added, or
#: multiplied, by the difference between contracts, or not at all.
type AdjustmentStyle = Literal["add", "mul"] | None

#: When a continuous future rolls to the next contract: on a calendar
#: schedule, or when the next contract's volume overtakes the current one's.
type RollStyle = Literal["calendar", "volume"]

#: Which contracts of a root symbol belong in its chain.
type ChainPredicate = Callable[[Future], bool]

ADJUSTMENT_STYLES: Set[AdjustmentStyle]
CHAIN_PREDICATES: dict[str, ChainPredicate]

class ContinuousFuture:
    """A stream of futures contracts of one root symbol, rolled from one
    contract to the next."""

    _kwargnames: ClassVar[frozenset[str]]

    def __init__(
        self,
        sid: int,
        root_symbol: str,
        offset: int,
        roll_style: RollStyle,
        start_date: pd.Timestamp,
        end_date: pd.Timestamp,
        exchange_info: ExchangeInfo,
        adjustment: AdjustmentStyle = None,
    ) -> None: ...
    @property
    def sid(self) -> int: ...
    @property
    def root_symbol(self) -> str: ...
    @property
    def offset(self) -> int: ...
    @property
    def roll_style(self) -> RollStyle: ...
    @property
    def start_date(self) -> pd.Timestamp: ...
    @property
    def end_date(self) -> pd.Timestamp: ...
    @property
    def exchange_info(self) -> ExchangeInfo: ...
    @property
    def adjustment(self) -> AdjustmentStyle: ...
    @property
    def exchange(self) -> str: ...
    @property
    def exchange_full(self) -> str: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __ne__(self, value: object, /) -> bool: ...
    def __lt__(self, value: SupportsIndex, /) -> bool: ...
    def __le__(self, value: SupportsIndex, /) -> bool: ...
    def __gt__(self, value: SupportsIndex, /) -> bool: ...
    def __ge__(self, value: SupportsIndex, /) -> bool: ...
    def to_dict(self) -> dict[str, object]: ...
    @classmethod
    def from_dict(cls, dict_: Mapping[str, object]) -> Self: ...
    def is_alive_for_session(self, session_label: pd.Timestamp) -> bool: ...
    def is_exchange_open(self, dt_minute: pd.Timestamp) -> bool: ...

class ContractNode:
    def __init__(self, contract: Future) -> None: ...
    @property
    def contract(self) -> Future: ...
    prev: ContractNode | None
    next: ContractNode | None
    def __rshift__(self, offset: int) -> ContractNode | None: ...
    def __lshift__(self, offset: int) -> ContractNode | None: ...

class OrderedContracts:
    """The contracts of a root symbol's chain, in order."""

    def __init__(
        self,
        root_symbol: str,
        contracts: Iterable[Future],
        chain_predicate: ChainPredicate | None = None,
    ) -> None: ...
    @property
    def root_symbol(self) -> str: ...
    @property
    def _head_contract(self) -> ContractNode: ...
    @property
    def sid_to_contract(self) -> dict[int, ContractNode]: ...
    @property
    def _start_date(self) -> int: ...
    @property
    def _end_date(self) -> int: ...
    @property
    def chain_predicate(self) -> ChainPredicate | None: ...
    @property
    def start_date(self) -> pd.Timestamp: ...
    @property
    def end_date(self) -> pd.Timestamp: ...
    def contract_before_auto_close(self, dt_value: int) -> int: ...
    def contract_at_offset(
        self, sid: int, offset: int, start_cap: int
    ) -> int | None: ...
    def active_chain(self, starting_sid: int, dt_value: int) -> np.ndarray: ...

def delivery_predicate(codes: Set[str], contract: Future) -> bool: ...
