"""Generate zipline/api.pyi.

Most of ``zipline.api`` is populated at import time by the ``@api_method``
decorator on ``TradingAlgorithm``, so type checkers can't see it. This
script writes a stub with the statically imported names re-exported and a
function for every API method, using the method's signature, annotations and
docstring. Names used in annotations are imported as ``zipline/algorithm.py``
imports them (including under ``TYPE_CHECKING``), or from
``zipline.algorithm`` if it defines them.

Usage::

    uv run python scripts/gen_api_stub.py
    uv run ruff check --fix --select I zipline/api.pyi
    uv run ruff format zipline/api.pyi

``tests/test_api_stub.py`` fails if the committed stub is out of date.
"""

import ast
import inspect
import textwrap
import types
from pathlib import Path

import zipline  # noqa: F401  (registers the API methods)
import zipline.algorithm
import zipline.api
from zipline.algorithm import TradingAlgorithm

STATIC = set(zipline.api._STATIC_ALL)


def reexport(name, obj):
    if isinstance(obj, types.ModuleType):
        parent, _, last = obj.__name__.rpartition(".")
        return f"from {parent} import {last} as {name}"
    return f"from {obj.__module__} import {obj.__qualname__} as {name}"


class _Source(str):
    """An annotation's source, which inspect renders unquoted."""

    def __repr__(self):
        return str(self)


def algorithm_imports():
    """Map each name ``zipline/algorithm.py`` imports or defines at module
    level to a stub line importing it.
    """
    tree = ast.parse(Path(zipline.algorithm.__file__).read_text())
    lines = {}
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and node.module != "__future__":
            for alias in node.names:
                as_ = f" as {alias.asname}" if alias.asname else ""
                lines[alias.asname or alias.name] = (
                    f"from {node.module} import {alias.name}{as_}"
                )
        elif isinstance(node, ast.Import):
            for alias in node.names:
                as_ = f" as {alias.asname}" if alias.asname else ""
                lines[alias.asname or alias.name] = f"import {alias.name}{as_}"
    for node in tree.body:
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name):
                    lines[target.id] = f"from zipline.algorithm import {target.id}"
    return lines


def annotation_names(annotation):
    """The names an annotation's source refers to."""
    tree = ast.parse(annotation, mode="eval")
    return {node.id for node in ast.walk(tree) if isinstance(node, ast.Name)}


def function_stub(name, names):
    """The stub of API method ``name``; adds the names its annotations use to
    ``names``.
    """
    method = getattr(TradingAlgorithm, name)
    sig = inspect.signature(method)

    def source(annotation):
        if annotation is inspect.Signature.empty:
            return annotation
        names.update(annotation_names(annotation))
        return _Source(annotation)

    params = [
        param.replace(annotation=source(param.annotation))
        for param in list(sig.parameters.values())[1:]  # drop self
    ]
    sig = sig.replace(
        parameters=params, return_annotation=source(sig.return_annotation)
    )
    doc = inspect.getdoc(method) or ""
    body = textwrap.indent(f'"""{doc}\n"""', "    ") if doc else "    ..."
    return f"def {name}{sig}:\n{body}\n"


def render():
    """The stub's source, before formatting."""
    imports = {reexport(n, getattr(zipline.api, n)) for n in STATIC}
    names = set()
    functions = [
        function_stub(n, names) for n in sorted(set(zipline.api.__all__) - STATIC)
    ]
    available = algorithm_imports()
    imports.update(available[n] for n in names - STATIC if n in available)
    header = "# Generated by scripts/gen_api_stub.py; do not edit by hand.\n"
    # A list, since api_method appends to it at import time.
    all_ = f"__all__: list[str] = {sorted(zipline.api.__all__)!r}\n"
    return (
        header
        + "\n".join(sorted(imports))
        + "\n\n"
        + all_
        + "\n\n"
        + "\n\n".join(functions)
    )


STUB_PATH = Path(zipline.__file__).parent / "api.pyi"


def main():
    STUB_PATH.write_text(render())
    print(f"wrote {STUB_PATH}")


if __name__ == "__main__":
    main()
