"""Generate zipline/api.pyi.

Most of ``zipline.api`` is populated at import time by the ``@api_method``
decorator on ``TradingAlgorithm``, so type checkers can't see it. This
script writes a stub with the statically imported names re-exported and a
function for every API method, using the method's signature and docstring.

Usage::

    uv run python scripts/gen_api_stub.py
    uv run ruff check --fix zipline/api.pyi && uv run ruff format zipline/api.pyi
"""

import inspect
import textwrap
import types
from pathlib import Path

import zipline  # noqa: F401  (registers the API methods)
import zipline.api
from zipline.algorithm import TradingAlgorithm

STATIC = set(zipline.api._STATIC_ALL)


def reexport(name, obj):
    if isinstance(obj, types.ModuleType):
        parent, _, last = obj.__name__.rpartition(".")
        return f"from {parent} import {last} as {name}"
    return f"from {obj.__module__} import {obj.__qualname__} as {name}"


def function_stub(name):
    method = getattr(TradingAlgorithm, name)
    sig = inspect.signature(method)
    params = list(sig.parameters.values())[1:]  # drop self
    sig = sig.replace(parameters=params, return_annotation=inspect.Signature.empty)
    doc = inspect.getdoc(method) or ""
    body = textwrap.indent(f'"""{doc}\n"""', "    ") if doc else "    ..."
    return f"def {name}{sig}:\n{body}\n"


def main():
    imports = sorted(reexport(n, getattr(zipline.api, n)) for n in STATIC)
    functions = [function_stub(n) for n in sorted(set(zipline.api.__all__) - STATIC)]
    header = "# Generated by scripts/gen_api_stub.py; do not edit by hand.\n"
    # A list, since api_method appends to it at import time.
    all_ = f"__all__: list[str] = {sorted(zipline.api.__all__)!r}\n"
    text = header + "\n".join(imports) + "\n\n" + all_ + "\n\n" + "\n\n".join(functions)
    out = Path(zipline.__file__).parent / "api.pyi"
    out.write_text(text)
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
